/**
 * Generated by: Raymond Truong
 * Date: 2025/08/21
 */
#pragma once

#include "logger.hpp"
#include "state_design.hpp"

namespace myapp {
    using namespace  state_design;
    inline void demo_state() {
        LOG_INFO("============ Demo State Design Pattern ===========");

        const auto  machine = make_unique<CoffeeMachine>(make_unique<IdleState>());
        machine->print_status();                  // Idle machine
        machine->next(); machine->print_status(); // Insert coin
        machine->next(); machine->print_status(); // Select coffee type
        machine->next(); machine->print_status(); // Preparing -> Finish
    }
}
