/**
 * Generated by: Raymond Truong
 * Date: 2025/08/21
 */

#pragma once
#include <iostream>
#include <string>
#include <memory>

namespace state_design {
    using namespace std;

    // Forward declaration
    class CoffeeMachine;

    // ---- State Interface ----
    class State {
    public:
        virtual ~State() = default;

        virtual void next(CoffeeMachine &context) = 0;

        virtual void print_status() const = 0;
    };

    class CoffeeMachine {
    private:
        unique_ptr<State> state;
        string coffe_type;

    public:
        explicit CoffeeMachine(unique_ptr<State> init_state) {
            state = std::move(init_state);
        }

        void set_state(unique_ptr<State> new_state) {
            state = std::move(new_state);
        }

        void next() {
            state->next(*this);
        }

        void print_status() const {
            state->print_status();
        }
    };

    // ---- Concrete States ----
    class IdleState final : public State {
    public:
        void next(CoffeeMachine &context) override;

        void print_status() const override {
            std::cout << "Machine is idle. Please insert a coin.\n";
        }
    };

    class HasCoinState final : public State {
    public:
        void next(CoffeeMachine &context) override;

        void print_status() const override {
            std::cout << "Coin inserted. Please select coffee type (Espresso/Latte/Cappuccino).\n";
        }
    };

    class SelectTypeState final : public State {
    public:
        void next(CoffeeMachine &context) override;

        void print_status() const override {
            std::cout << "Coffee type selected. Preparing your drink...\n";
        }
    };

    class FinishState final : public State {
    public:
        void next(CoffeeMachine &context) override {
            std::cout << "Coffee already finished. Please take your cup.\n";
        }

        void print_status() const override {
            std::cout << "✅ Your " << "coffee" << " is ready. Enjoy!\n";
        }
    };

    // ---- Transitions ----
    inline void IdleState::next(CoffeeMachine &context) {
        context.set_state(make_unique<HasCoinState>());
    }

    inline void HasCoinState::next(CoffeeMachine &context) {
        context.set_state(make_unique<SelectTypeState>());
    }

    inline void SelectTypeState::next(CoffeeMachine &context) {
        context.set_state(make_unique<FinishState>());
    }
}
