/**
 * Generated by: Raymond Truong
 * Date: 2025/08/22
 */
#pragma once

#include "logger.hpp"
#include "visitor_method_design.hpp"


using namespace visitor_design;
namespace myapp {
    inline void demo_visitor_method() {
        LOG_INFO("============ Demo Visitor Method Design Pattern ===========");

        Monkey monkey;
        Lion lion;
        Dolphin dolphin;

        AnimalSpeak animal_speak;
        monkey.accept(animal_speak);
        lion.accept(animal_speak);
        dolphin.accept(animal_speak);

        cout<< "================ \n";

        AnimalJump animal_jump;
        monkey.accept(animal_jump);
        lion.accept(animal_jump);
        dolphin.accept(animal_jump);

    }

}