/**
 * Generated by: Raymond Truong
 * Date: 2025/08/22
 */

#pragma once
#include <iostream>

using namespace std;

namespace visitor_design {
    // Forward declarations
    class Monkey;
    class Lion;
    class Dolphin;

    class AnimalVisitor {
    public:
        virtual ~AnimalVisitor() = default;

        virtual void visit_monkey(Monkey &monkey) = 0;

        virtual void visit_lion(Lion &lion) = 0;

        virtual void visit_dolphin(Dolphin &dolphin) = 0;
    };

    // =========== Visitee ===========
    class Animal {
    public:
        virtual void accept(AnimalVisitor &visitor) =0;

        virtual ~Animal() = default;
    };

    class Monkey final : public Animal {
    public:
        ~Monkey() override = default;

        void accept(AnimalVisitor &visitor) override {
            visitor.visit_monkey(*this);
        }
    };

    class Lion final : public Animal {
    public:
        ~Lion() override = default;

        void accept(AnimalVisitor &visitor) override {
            visitor.visit_lion(*this);
        }
    };

    class Dolphin final : public Animal {
    public:
        ~Dolphin() override = default;

        void accept(AnimalVisitor &visitor) override {
            visitor.visit_dolphin(*this);
        }
    };

    // =========== Concrete Visitors ===========

    class AnimalSpeak final : public AnimalVisitor {
    public:
        ~AnimalSpeak() override = default;

        void visit_monkey(Monkey &monkey) override {
            cout << " Monkey shout: Ooh oo aah! \n";
        }

        void visit_lion(Lion &lion) override {
            cout << " Lion roar: Roaaarr! \n";
        }

        void visit_dolphin(Dolphin &dolphin) override {
            cout << " Dolphin speak:Tuut tuut tuut! \n";
        }
    };

    class AnimalJump final : public AnimalVisitor {
    public:
        ~AnimalJump() override = default;

        void visit_monkey(Monkey &monkey) override {
            cout << " Monkey jumped 5 meter heigh on the tree \n";
        }

        void visit_lion(Lion &lion) override {
            cout << " Lion jumped 3 meters on the ground! \n";
        }

        void visit_dolphin(Dolphin &dolphin) override {
            cout << " Dolphin jumped 2 meters out of the water!  \n";
        }
    };
}
