/**
 * Generated by: Raymond Truong
 * Date: 2025/08/08
 */
#pragma once

#include <memory>
#include "logger.hpp"
#include "JobObserver.hpp"

namespace myapp {
    using namespace  std;
    using namespace  observer_design;

    inline void demo_observer() {
        LOG_INFO("============ Demo Observer Design Pattern ===========");

        EmploymentAgency agency;

        JobSeeker seeker1("Alice");
        JobSeeker seeker2("Bob");
        JobSeeker seeker3("Charlie");

        agency.attach(&seeker1);
        agency.attach(&seeker2);
        agency.attach(&seeker3);

        agency.addJob("C++ Developer at OpenAI");

        agency.detach(&seeker2);
        std::cout << "\n⚠️Bob has been removed from the observer list and won't get new job updates anymore.\n";

        agency.addJob("Systems Engineer at Google");
      
    }

}
