/**
 * Generated by: Raymond Truong
 * Date: 2025/08/21
 */
#pragma once

#include <memory>
#include "logger.hpp"
#include "template_method.hpp"

namespace myapp {
    using namespace  std;


    inline void demo_template_method() {
        LOG_INFO("============ Demo Template Method Design Pattern ===========");

        const auto chicken_noodles = make_unique<ChickenNoodlesCooking>();
        chicken_noodles->prepare_recipe();

        cout << " --------------- \n";

        const auto fish_noodles = make_unique<FishNoodlesCooking>();
        fish_noodles->prepare_recipe();
    }

}
