/**
 * Generated by: Raymond Truong
 * Date: 2025/08/21
 */

#pragma once
#include <iostream>

using namespace std;

namespace myapp {
    class NoodlesCooking {
    public:
        virtual ~NoodlesCooking() = default;

        void prepare_recipe() {
            boil_water();
            add_vegetables();
            add_noodles();
            cook_noodles();
            serve();
        }

    private:
        static void boil_water() {
            cout << "🧪Boiling water... \n";
        }

        virtual void add_vegetables() = 0;

        virtual void add_noodles() = 0;

        virtual void cook_noodles() = 0;

        static void serve() {
            cout << "✅Ready to serve... \n";
        }
    };

    class ChickenNoodlesCooking final : public NoodlesCooking {
        void add_vegetables() override {
            cout << " => 🍜🍗Add vegetable: carrot, chicken... \n";
        }

        void add_noodles() override {
            cout << " => 🍜🍗Add chicken noodles... \n";
        }

        void cook_noodles() override {
            cout << " => 🍜🍗Cooking in 5 minutes... \n";
        }
    };

    class FishNoodlesCooking final : public NoodlesCooking {
        void add_vegetables() override {
            cout << " => 🍜🐟 Adding vegetables: tomato, herbs... \n";
        }

        void add_noodles() override {
            cout << " => 🍜🐟 Adding fish noodles... \n";
        }

        void cook_noodles() override {
            cout << " => 🍜🐟 Cooking for 5 minutes... \n";
        }
    };
}
