/**
 * Generated by: Raymond Truong
 * Date: 2025/07/22
 */

#include "builder.hpp"

namespace myapp {
    // Pizza display method implementation
    void Pizza::display() const {
        cout << "Pizza Details:\n";
        cout << "  Size: " << size_ << "\n";
        cout << "  Add-ons: ";
        
        bool has_addons = false;
        if (has_egg_) {
            cout << "Egg ";
            has_addons = true;
        }
        if (has_cheese_) {
            cout << "Cheese ";
            has_addons = true;
        }
        if (has_bacon_) {
            cout << "Bacon ";
            has_addons = true;
        }
        if (has_fish_) {
            cout << "Fish ";
            has_addons = true;
        }
        if (has_vegetable_) {
            cout << "Vegetable ";
            has_addons = true;
        }
        
        if (!has_addons) {
            cout << "None";
        }
        cout << "\n\n";
    }
}
