/**
 * Generated by: Raymond Truong
 * Date: 2025/07/22
 */
#pragma once
#include "builder.hpp"
#include "logger.hpp"

using namespace myapp;

inline void demo_builder() {
    LOG_INFO("============ Demo Creational design > Builder Pattern ===========");
    // Create a custom pizza with specific add-ons
    // Create a breakfast pizza
    cout << "Creating a breakfast pizza:\n";
    const auto breakfast_pizza = PizzaBuilder("Medium")
        .add_egg()
        .add_cheese()
        .add_bacon()
        .build();
    breakfast_pizza->display();
    
    // Create a vegetarian pizza
    cout << "Creating a vegetarian pizza:\n";
    const auto veggie_pizza = PizzaBuilder("Small")
        .add_cheese()
        .add_vegetable()
        .build();
    veggie_pizza->display();
}
