/**
 * Generated by: Raymond Truong
 * Date: 2025/08/21
 */
#pragma once

#include "logger.hpp"
#include "strategy_design.hpp"

namespace myapp {

    inline void demo_strategy() {
        LOG_INFO("============ Demo Strategy Design Pattern ===========");

        const auto cart = make_unique<strategy_design::ShoppingCart>();
        cart->add_item(make_unique<strategy_design::Item>("vegetable",5));
        cart->add_item(make_unique<strategy_design::Item>("meat",20));
        cart->add_item(make_unique<strategy_design::Item>("wine",50));
        cart->remove_item("wine");
        cout<<"Total price: $" << cart->calculate_total() << "\n";

        LOG_INFO("Checkout using Credit Card:");
        strategy_design::CreditCardPayment cc("1234-5678-9012");
        cart->checkout(cc);

        LOG_INFO("Checkout using Paypal:");
        strategy_design::PaypalPayment paypal("paypal_user@gmail.com");
        cart->checkout(paypal);

    }

}
