/**
 * Generated by: Raymond Truong
 * Date: 2025/08/21
 */

#pragma once

using namespace std;

namespace strategy_design {
    class PaymentStrategy {
    public:
        virtual ~PaymentStrategy() = default;

        virtual void pay(int amount) = 0;
    };

    // ---- Concrete Payment Strategies ----
    class CreditCardPayment final : public PaymentStrategy {
        string card_number_;

    public:
        explicit CreditCardPayment(const string &card_number) {
            card_number_ = card_number;
        }

        void pay(const int amount) override {
            std::cout << "Paid $" << amount << " using credit card: " << card_number_ << "\n";
        }
    };

    class PaypalPayment final : public PaymentStrategy {
        string email_;

    public:
        explicit PaypalPayment(const string &email) {
            email_ = email;
        }

        void pay(const int amount) override {
            std::cout << "Paid $" << amount << " using Paypal email: " << email_ << "\n";
        }
    };

    // ---- Context ----
    class Item {
        string item_id_;
        int price_;

    public:
        Item(const string &item_id, const int price) {
            item_id_ = item_id;
            price_ = price;
        }

        [[nodiscard]] int get_price() const { return price_; }
        [[nodiscard]] string get_id() const { return item_id_; }
    };

    class ShoppingCart {
        vector<unique_ptr<Item> > items;

    public:
        void add_item(unique_ptr<Item> item) {
            cout<<"Add "<<item->get_id()<<", price: "<<item->get_price()<<"$"<<"\n";
            items.push_back(std::move(item));
        }

        void remove_item(const std::string &id) {
            const auto it = ranges::remove_if(items,
                                              [&](const std::unique_ptr<Item> &item) {
                                                  if (item->get_id() == id) {
                                                      std::cout << "Removed " << item->get_id()
                                                              << ", price: " << item->get_price() << "$\n";
                                                      return true;
                                                  }
                                                  return false;
                                              }).begin();
            items.erase(it, items.end());
        }

        [[nodiscard]] int calculate_total() const {
            int sum = 0;
            for (const auto &item: items) {
                sum += item->get_price();
            }
            return sum;
        }

        void checkout(PaymentStrategy &payment_strategy) const {
            const int total = calculate_total();
            payment_strategy.pay(total);
        }
    };
}
