/**
* Generated by: Raymond Truong
 * Date: 2025/08/06
 */
#pragma once

#include <memory>
#include "logger.hpp"
#include "factory_method_design.hpp"

namespace myapp {
    using namespace  std;

    inline void demo_factory_method() {
        LOG_INFO("============ Demo Factory Method Design Pattern ===========");

        const std::unique_ptr<CarStore> sport_store = std::make_unique<SportsCarStore>();
        sport_store->order_car();  // Output: Sports car is made.

        const std::unique_ptr<CarStore> economy_store = std::make_unique<EconomyCarStore>();
        economy_store->order_car();  // Output: Economy car is made.
    }
}