/**
 * Generated by: Raymond Truong
 * Date: 2025/08/08
 */
#pragma once

#include <memory>

#include "prototype.hpp"
#include "logger.hpp"

namespace myapp {
    using namespace  std;
    using namespace  prototype_design;

    inline void demo_prototype() {
        LOG_INFO("============ Demo Prototype Design Pattern ===========");

        const unique_ptr<Shape> originalCircle = make_unique<Circle>(10.0);
        const unique_ptr<Shape> clonedCircle = originalCircle->clone();

        const unique_ptr<Shape> originalRectangle = make_unique<Rectangle>(50.0, 100.0);
        const unique_ptr<Shape> clonedRectangle = originalRectangle->clone();

        cout << "Original shapes:\n";
        originalCircle->draw();
        originalRectangle->draw();

        cout << "\nCloned shapes:\n";
        clonedCircle->draw();
        clonedRectangle->draw();
    }

}