/**
 * Generated by: Raymond Truong
 * Date: 2025/07/22
 */

#pragma once
#include <iostream>

#include "behavioral_patterns/observer/demo_observer.hpp"
#include "creational_patterns/abstract_factory/demo_abstract_factory.hpp"
#include "creational_patterns/builder/demo_builder.hpp"
#include "creational_patterns/factory_method/demo_factory_method.hpp"
#include "creational_patterns/prototype/demo_prototype.hpp"
#include "creational_patterns/singleton/demo_singleton.hpp"

using namespace std;
namespace myapp {
    typedef enum {
        singleton,
        builder,
        factory_method,
        abstract_factory,
        prototype,
        observer,
    } demo_type;

    class DemoExample {
    public:
        static void create_demo(demo_type type) {
            switch (type) {
                case singleton:
                    return demo_singleton();
                case builder:
                    return demo_builder();
                case factory_method:
                    return demo_factory_method();
                case abstract_factory:
                    return demo_abstract_factory();
                case prototype:
                    return demo_prototype();
                case observer:
                    return demo_observer();


                default: cout << "No example!" << endl;
            }
        }

    };
} // namespace myapp
