/**
 * Generated by: Raymond Truong
 * Date: 2025/07/22
 */

#pragma once
#include "Creational/D01_Singleton/demo_singleton.hpp"

namespace myapp {
    typedef enum {
        singleton,
    } demo_type;

    class DemoExample {
    public:
        static void create_demo(demo_type type) {
            switch (type) {
                case singleton:
                    return demo_singleton();

                default: std::cout << "No example!" << std::endl;
            }
        }

    };
} // namespace myapp