/**
 * Generated by: Raymond Truong
 * Date: 2025/07/22
 */

#pragma once
#include <iostream>
#include "Creational/D01_Singleton/demo_singleton.hpp"
#include "Creational/D02_Builder/demo_builder.hpp"

using namespace std;
namespace myapp {
    typedef enum {
        singleton,
        builder,
    } demo_type;

    class DemoExample {
    public:
        static void create_demo(demo_type type) {
            switch (type) {
                case singleton:
                    return demo_singleton();
                case builder:
                    return demo_builder();

                default: cout << "No example!" << endl;
            }
        }

    };
} // namespace myapp
